version: '3.9'
services:
  web-mirror:
    image: drumsergio/web-mirror:latest
    volumes:
      - G:/:/data/
  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - G:/:/usr/share/nginx/html
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - "80:80"

volumes:
  web:
    # driver_opts:
    #   type: nfs 
    #   o: "addr=192.168.9.99" 
    #   device: ":/Multimedia/Musica"